In [2]:
#QUESTION 1
import pandas as pd

info = {'Name':['Rohit','Nikhil','Krishan','Deepak','Kartikey'],'Age':[20,20,19,21,22],'Ph no.':['8527378713','9876874587','9845786642','8769054563','7890123456'],'Email':['rohityadav7946@gmail.com','nikhil@gmail.com','krishan@gmail.com','deepak@gmail.com','kartikey@gmail.com']}

df=pd.DataFrame(info)
df = df[['Name','Age','Ph no.','Email']]
print(df)

df.loc[5]=['Kshitij',19,'9874563210','kshitij@gmail.com']
print(df)

       Name  Age      Ph no.                     Email
0     Rohit   20  8527378713  rohityadav7946@gmail.com
1    Nikhil   20  9876874587          nikhil@gmail.com
2   Krishan   19  9845786642         krishan@gmail.com
3    Deepak   21  8769054563          deepak@gmail.com
4  Kartikey   22  7890123456        kartikey@gmail.com
       Name  Age      Ph no.                     Email
0     Rohit   20  8527378713  rohityadav7946@gmail.com
1    Nikhil   20  9876874587          nikhil@gmail.com
2   Krishan   19  9845786642         krishan@gmail.com
3    Deepak   21  8769054563          deepak@gmail.com
4  Kartikey   22  7890123456        kartikey@gmail.com
5   Kshitij   19  9874563210         kshitij@gmail.com

In [3]:
#QUESTION2
weather = pd.read_csv('https://raw.githubusercontent.com/Shreyas3108/Weather/master/weather.csv')

In [4]:
#QUESTION 2(a)
weather.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,11/1/2007,Canberra,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,11/2/2007,Canberra,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,11/3/2007,Canberra,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,11/4/2007,Canberra,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,11/5/2007,Canberra,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [6]:
#QUESTION 2(b)
weather.head(10)

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,11/1/2007,Canberra,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,11/2/2007,Canberra,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,11/3/2007,Canberra,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,11/4/2007,Canberra,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,11/5/2007,Canberra,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
5,11/6/2007,Canberra,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,...,57,1023.8,1021.7,7,5,10.9,14.8,No,0.2,No
6,11/7/2007,Canberra,6.1,18.2,0.2,4.2,8.4,SE,43.0,SE,...,47,1024.6,1022.2,4,6,12.4,17.3,No,0.0,No
7,11/8/2007,Canberra,8.3,17.0,0.0,5.6,4.6,E,41.0,SE,...,57,1026.2,1024.2,6,7,12.1,15.5,No,0.0,No
8,11/9/2007,Canberra,8.8,19.5,0.0,4.0,4.1,S,48.0,E,...,48,1026.1,1022.7,7,7,14.1,18.9,No,16.2,Yes
9,11/10/2007,Canberra,8.4,22.8,16.2,5.4,7.7,E,31.0,S,...,32,1024.1,1020.7,7,1,13.3,21.7,Yes,0.0,No

In [7]:
#QUESTION 2(c)
weather.iloc[0:15,0:10].describe()

        MinTemp    MaxTemp   Rainfall  Evaporation   Sunshine  WindGustSpeed
count  15.00000  15.000000  15.000000    15.000000  15.000000      15.000000
mean    9.62000  22.873333   4.426667     5.666667   8.993333      43.400000
std     2.56632   5.386553  10.644883     1.490286   3.315864      13.725888
min     6.10000  15.500000   0.000000     3.400000   3.300000      30.000000
25%     8.15000  17.600000   0.000000     4.300000   7.000000      35.000000
50%     8.80000  23.400000   0.000000     5.600000   9.100000      41.000000
75%    11.10000  27.100000   3.200000     6.700000  12.150000      46.000000
max    14.00000  31.200000  39.800000     8.800000  13.100000      85.000000

In [8]:
#QUESTION 2(d)
weather.tail()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
361,10/27/2008,Canberra,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,10/28/2008,Canberra,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,10/29/2008,Canberra,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,10/30/2008,Canberra,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,10/31/2008,Canberra,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [11]:
#QUESTION 2(e)
weather.iloc[:,1].describe()

count          366
unique           1
top       Canberra
freq           366
Name: Location, dtype: object